all:
  .config:
    oauth:
      key: dj0yJmk9MG1JbXhNTm96TnhlJmQ9WVdrOVExQnJXVlo2TlRZbWNHbzlNVEF6TVRNd056TTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD0yZQ--
      secret: c922ed5b0ceb42a1f89a985ddc82a957c0d637bd 
      version: 1
      request_token_url: https://api.login.yahoo.com/oauth/v2/get_request_token
      request_auth_url: https://api.login.yahoo.com/oauth/v2/request_auth
      access_token_url: https://api.login.yahoo.com/oauth/v2/get_token
      callback: "@oauth_callback"
      api: http://social.yahooapis.com/v1/user/%s/contacts