oauth_index:
  url: /oauth
  param: { module: oauth, action: index }
  
oauth_callback:
  url: /oauth/callback
  param: { module: oauth, action: callback }
  
oauth_api:
  url: /oauth/api
  param: { module: oauth, action: api }